"""
Institutional asset opinions — curated views from major banks/asset managers.
Reflects publicly known positioning as of May 2026.
"""

OPINIONS = [
    # ── US EQUITIES ──
    {
        "institution": "Goldman Sachs",
        "asset": "S&P 500",
        "asset_class": "Equities",
        "short_term": "Overweight",
        "short_term_note": "Strong earnings resilience and AI capex cycle support near-term upside. Expect dip-buying on tariff noise.",
        "short_term_target": "5,800",
        "long_term": "Neutral",
        "long_term_note": "Valuations stretched at 21x forward P/E. Tariff uncertainty and margin pressure cap 12m upside.",
        "long_term_target": "6,000",
        "updated": "2026-04-28",
    },
    {
        "institution": "JPMorgan",
        "asset": "S&P 500",
        "asset_class": "Equities",
        "short_term": "Neutral",
        "short_term_note": "Cautious near-term — tariff escalation risk not fully priced. Prefer quality and defensives.",
        "short_term_target": "5,600",
        "long_term": "Overweight",
        "long_term_note": "Fed easing cycle + earnings growth of ~10% support re-rating over 12-18 months.",
        "long_term_target": "6,200",
        "updated": "2026-04-25",
    },
    {
        "institution": "Morgan Stanley",
        "asset": "S&P 500",
        "asset_class": "Equities",
        "short_term": "Underweight",
        "short_term_note": "Leading indicators point to earnings deceleration. High-yield spreads widening is a warning sign.",
        "short_term_target": "5,200",
        "long_term": "Neutral",
        "long_term_note": "Macro backdrop improves if Fed cuts 3x. Rotate into cyclicals on confirmation of soft landing.",
        "long_term_target": "5,800",
        "updated": "2026-04-22",
    },
    # ── EUROPEAN EQUITIES ──
    {
        "institution": "BlackRock",
        "asset": "Euro Stoxx 50",
        "asset_class": "Equities",
        "short_term": "Overweight",
        "short_term_note": "ECB cutting cycle and weak EUR boost export earnings. Valuations attractive vs US at 13x P/E.",
        "short_term_target": "5,400",
        "long_term": "Overweight",
        "long_term_note": "Fiscal stimulus (Germany defence, EU fund) is a structural re-rating catalyst not yet fully priced.",
        "long_term_target": "5,800",
        "updated": "2026-04-30",
    },
    {
        "institution": "UBS",
        "asset": "Euro Stoxx 50",
        "asset_class": "Equities",
        "short_term": "Neutral",
        "short_term_note": "Near-term headwinds from trade war exposure. Watch German PMI for confirmation of recovery.",
        "short_term_target": "5,100",
        "long_term": "Overweight",
        "long_term_note": "Structural fiscal shift in Europe is a multi-year tailwind. Add on dips toward 4,800.",
        "long_term_target": "5,600",
        "updated": "2026-04-24",
    },
    # ── US TREASURIES ──
    {
        "institution": "Goldman Sachs",
        "asset": "US 10Y Treasury",
        "asset_class": "Fixed Income",
        "short_term": "Neutral",
        "short_term_note": "10Y range-bound 4.2–4.6% near-term. Supply pressure from deficits offsets Fed cut expectations.",
        "short_term_target": "4.35%",
        "long_term": "Overweight",
        "long_term_note": "3 Fed cuts by end-2026 should drag 10Y toward 3.8%. Bonds attractive vs equities on risk-adjusted basis.",
        "long_term_target": "3.80%",
        "updated": "2026-04-28",
    },
    {
        "institution": "JPMorgan",
        "asset": "US 10Y Treasury",
        "asset_class": "Fixed Income",
        "short_term": "Overweight",
        "short_term_note": "Flight-to-safety bid on tariff uncertainty supports near-term duration. Strong demand at recent auctions.",
        "short_term_target": "4.10%",
        "long_term": "Neutral",
        "long_term_note": "Fiscal deficit trajectory is bearish for long bonds. Prefer 2Y–5Y part of curve.",
        "long_term_target": "4.20%",
        "updated": "2026-04-25",
    },
    # ── GOLD ──
    {
        "institution": "Goldman Sachs",
        "asset": "Gold",
        "asset_class": "Commodities",
        "short_term": "Overweight",
        "short_term_note": "Central bank buying and geopolitical risk premium keep gold bid. $3,200–$3,400 near-term range.",
        "short_term_target": "$3,300",
        "long_term": "Overweight",
        "long_term_note": "De-dollarisation trend and EM central bank accumulation is a structural bid. Target $3,700 by end-2026.",
        "long_term_target": "$3,700",
        "updated": "2026-04-29",
    },
    {
        "institution": "Citi",
        "asset": "Gold",
        "asset_class": "Commodities",
        "short_term": "Overweight",
        "short_term_note": "Macro uncertainty and real rate decline support. ETF inflows accelerating — momentum positive.",
        "short_term_target": "$3,250",
        "long_term": "Overweight",
        "long_term_note": "Fed easing + dollar weakness = sustained tailwind. Long gold as portfolio hedge into 2027.",
        "long_term_target": "$3,500",
        "updated": "2026-04-27",
    },
    # ── OIL ──
    {
        "institution": "Morgan Stanley",
        "asset": "WTI Crude",
        "asset_class": "Commodities",
        "short_term": "Underweight",
        "short_term_note": "OPEC+ supply increase and weak China demand weigh on near-term price. $65–$72 range likely.",
        "short_term_target": "$68",
        "long_term": "Neutral",
        "long_term_note": "Supply discipline from OPEC+ prevents collapse below $60. Global growth recovery needed for re-rating.",
        "long_term_target": "$75",
        "updated": "2026-04-23",
    },
    {
        "institution": "Goldman Sachs",
        "asset": "WTI Crude",
        "asset_class": "Commodities",
        "short_term": "Neutral",
        "short_term_note": "Inventory builds and demand uncertainty balanced by OPEC+ flexibility. Tactically neutral.",
        "short_term_target": "$70",
        "long_term": "Overweight",
        "long_term_note": "Under-investment in supply is a 2027+ catalyst. Emerging market demand recovery underpriced.",
        "long_term_target": "$82",
        "updated": "2026-04-28",
    },
    # ── USD ──
    {
        "institution": "JPMorgan",
        "asset": "US Dollar (DXY)",
        "asset_class": "FX",
        "short_term": "Underweight",
        "short_term_note": "Dollar weakening on Fed cut expectations and tariff policy uncertainty reducing confidence in USD assets.",
        "short_term_target": "99",
        "long_term": "Neutral",
        "long_term_note": "Structural USD weakness limited by relative US growth outperformance. Range 98–105 over 12m.",
        "long_term_target": "101",
        "updated": "2026-04-25",
    },
    {
        "institution": "Deutsche Bank",
        "asset": "US Dollar (DXY)",
        "asset_class": "FX",
        "short_term": "Neutral",
        "short_term_note": "Short-term range-bound. Tariff news flow drives vol but no directional conviction near-term.",
        "short_term_target": "101",
        "long_term": "Underweight",
        "long_term_note": "Fiscal deficit expansion and eroding confidence in US institutions is a long-term dollar negative.",
        "long_term_target": "96",
        "updated": "2026-04-22",
    },
    # ── BITCOIN ──
    {
        "institution": "BlackRock",
        "asset": "Bitcoin",
        "asset_class": "Crypto",
        "short_term": "Overweight",
        "short_term_note": "ETF inflows remain strong. Bitcoin increasingly treated as digital gold amid macro uncertainty.",
        "short_term_target": "$105,000",
        "long_term": "Overweight",
        "long_term_note": "Institutional adoption flywheel accelerating. $150K+ plausible if sovereign adoption expands.",
        "long_term_target": "$150,000",
        "updated": "2026-04-30",
    },
    {
        "institution": "Morgan Stanley",
        "asset": "Bitcoin",
        "asset_class": "Crypto",
        "short_term": "Neutral",
        "short_term_note": "Risk-off environment could weigh short-term. Correlation to equities still elevated — watch macro.",
        "short_term_target": "$90,000",
        "long_term": "Overweight",
        "long_term_note": "Halving cycle and regulatory clarity are long-term tailwinds. Build position on dips to $80K.",
        "long_term_target": "$130,000",
        "updated": "2026-04-24",
    },
    # ── CHINESE EQUITIES ──
    {
        "institution": "UBS",
        "asset": "CSI 300 (China)",
        "asset_class": "Equities",
        "short_term": "Underweight",
        "short_term_note": "Trade war escalation directly hits export sectors. Stimulus measures insufficient to offset near-term drag.",
        "short_term_target": "3,600",
        "long_term": "Neutral",
        "long_term_note": "Domestic consumption recovery and policy pivot could re-rate. Selective in consumer and tech names.",
        "long_term_target": "4,200",
        "updated": "2026-04-26",
    },
    {
        "institution": "Citi",
        "asset": "CSI 300 (China)",
        "asset_class": "Equities",
        "short_term": "Neutral",
        "short_term_note": "PBoC easing and fiscal stimulus offer floor. Tech sector re-rating from AI investment is a bright spot.",
        "short_term_target": "3,900",
        "long_term": "Overweight",
        "long_term_note": "Valuations at 10x P/E are compelling if trade deal progress materialises in H2 2026.",
        "long_term_target": "4,600",
        "updated": "2026-04-28",
    },
]

ASSET_CLASSES = sorted(set(o["asset_class"] for o in OPINIONS))
INSTITUTIONS  = sorted(set(o["institution"] for o in OPINIONS))


def get_opinions(asset_class: str | None = None, institution: str | None = None) -> dict:
    filtered = OPINIONS
    if asset_class:
        filtered = [o for o in filtered if o["asset_class"].lower() == asset_class.lower()]
    if institution:
        filtered = [o for o in filtered if o["institution"].lower() == institution.lower()]
    return {
        "opinions": filtered,
        "asset_classes": ASSET_CLASSES,
        "institutions": INSTITUTIONS,
    }
